---
- debug:
    msg: "Instantiate chaincode {{ CC_NAME }}:{{ CC_VERSION }} on channel {{ CHANNEL_NAME }}"

- name: Select a peer and orderer for chaincode instantiation.
  set_fact:
    peer: "{{ allpeers | random }}"
    orderer: "{{ allorderers | random }}"
    isuffix: "{{ (fabric.release is version('2.0', '>='))|ternary('2', '')}}"

- name: Create chaincode instantiate script
  template:
    src: "{{ pjroot }}/playbooks/ops/templates/ccinstantiate{{ isuffix }}.j2"
    dest: "{{ pjroot }}/vars/run/ccinstantiate.sh"
    mode: +x

- name: Run the chaincode instantiate script on cli container
  command: >-
    docker exec cli /vars/run/ccinstantiate.sh
