---
- name: Start fabric operations
  hosts: minifab
  gather_facts: no
  connection: local
  vars:
    pjroot: "{{ playbook_dir }}"
  vars_files:
    - "./spec.yaml"
    - "./playbooks/ops/opnames.yaml"
  tasks:
    - set_fact:
        allops: "{{ mode.split(',')|list }}"
        status_flag: "Success"

    - set_fact:
        OPNAMES: "{{ OPNAMES | combine({'ccinstantiate': 'cc commit'}) }}"
      when: IMAGETAG is version('2.0', '>=')

    - set_fact:
        allops: "{{ allops | difference(['ccapprove']) }}"
      when: IMAGETAG is version('2.0', '<')

    - meta: end_play
      when: allops|length == 0

    - set_fact:
        msgops: "{{ (msgops|default([])) + [OPNAMES[item]] }}"
      with_items: "{{ allops }}"

    - name: "Fabric operations"
      debug:
        msg: "{{ msgops|join(', ') }}"
      tags: [print_action]

    - name: "Process configuration"
      include_tasks: "playbooks/common/config_apply.yaml"

    - name: Check if external node endpoint exists
      stat: 
        path: "{{ pjroot }}/vars/extendpoints.yaml"
      register: exflag

    - name: "Handling external orderers"
      include_tasks: "playbooks/common/externalnodes.yaml"
      when: exflag.stat.exists == true

    - name: Do all the requested fabric operations
      include_tasks: "playbooks/ops/{{ op }}/apply.yaml"
      loop: "{{ allops }}"
      loop_control:
        loop_var: op
      when: status_flag == "Success" and (allorderers|length) > 0 and (allpeers|length) > 0
