---
- name: Start fabric operations
  hosts: vm
  connection: local
  vars:
    pjroot: "{{ playbook_dir }}"
  vars_files:
    - "./spec.yaml"
  tasks:
    - set_fact:
        allops: "{{ mode.split(',')|list }}"
        status_flag: "Success"

    - name: "Process configuration"
      include_tasks: "playbooks/common/config_apply.yaml"

    - name: Check if external orderers endpoints exists
      stat: 
        path: "{{ pjroot }}/vars/orderendpoints.yaml"
      register: exordererflag

    - name: "Handling external orderers"
      include_tasks: "playbooks/common/externalorderers.yaml"
      when: exordererflag.stat.exists == true and (allorderers|length) == 0

    - name: Do all the requested fabric operations
      include_tasks: "playbooks/ops/{{ op }}/apply.yaml"
      loop: "{{ allops }}"
      loop_control:
        loop_var: op
      when: status_flag == "Success"
