---
- name: Get start timestamp
  hosts: vm
  connection: local
  vars:
    pjroot: "{{ playbook_dir }}"
  vars_files:
    - "./spec.yaml"
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"
        status_flag: "Success"
    - name: "{{ mode }} configuration"
      include_tasks: "playbooks/common/config_apply.yaml"
      tags: "common"
    - name: "{{ mode }} Fabric binary files"
      include_tasks: "playbooks/getbin/tasks/{{ mode }}.yaml"
      tags: "bin"
    - name: "{{ mode }} certificates and artifacts"
      include_tasks: "playbooks/certsetup/tasks/{{ mode }}.yaml"
      tags: "certs"
    - name: "{{ mode }} Fabric network and nodes"
      include_tasks: "playbooks/nodes/tasks/{{ mode }}.yaml"
      tags: "nodes"

- name: Inform the installer
  hosts: vm
  connection: local
  tasks:
    - name: Summary
      debug:
        msg: >-
          The work load started at: {{ hostvars.vm.starttime.time }}.
          Finished at: {{ ansible_date_time.time }}.
          Total time took: {{ (ansible_date_time.epoch|int) - (hostvars.vm.starttime.epoch|int) }} seconds
