---
- debug:
    msg: "Installing chaincode {{ CC_NAME}}:{{ CC_VERSION }}"

- name: "Install chaincode onto {{ peer }}"
  include_tasks: "installcc.yaml"
  loop: "{{ allpeers }}"
  loop_control:
    loop_var: peer
  when: status_flag == "Success"
