---
- name: Initialize the success flag
  set_fact:
    status_flag: "Success"

- name: Select an orderer for chaincode install
  set_fact:
    orderer: "{{ allorderers | random }}"
    langsuffix: "{{ {'go': 'lang', 'node':'', 'java':''} }}"

- name: "Install chaincode onto all peers"
  include_tasks: "installcc.yaml"
  loop: "{{ allpeers }}"
  loop_control:
    loop_var: installpeer
  when: status_flag == "Success"
