---
- name: Initialize the success flag
  set_fact:
    status_flag: "Success"

- name: Select an orderer for chaincode install
  set_fact:
    orderer: "{{ allorderers | random }}"
    langsuffix: "{{ {'go': 'lang', 'node':'', 'java':''} }}"

- name: Set approval peer for each org
  set_fact:
    orgapprover: >-
      {{ orgapprover | default({}) | combine({
        item: allpeers|selectattr('org','equalto',item)|list|random}) }}
  with_items: "{{ peerorgs }}"
  when: fabric.release is version('2.0', '>=')

- name: "Install chaincode onto all peers"
  include_tasks: "installcc.yaml"
  loop: "{{ allpeers }}"
  loop_control:
    loop_var: installpeer
  when: status_flag == "Success"
