---
- debug:
    msg: "Ready to install chaincode onto {{ peer.fullname }}"

- name: Create chaincode install script
  template:
    src: "{{ pjroot }}/playbooks/ops/templates/ccinstall.j2"
    dest: "{{ pjroot }}/vars/run/ccinstall.sh"
    mode: +x

- name: Run the chaincode install script on cli container
  command: >-
    docker exec cli /vars/run/ccinstall.sh
  register: result

- name: Set the status flag based on the return value
  set_fact:
    status_flag: "{{ (result.rc == 0)|ternary('Success', 'Failure') }}"
