---
- debug:
    msg: "Installing  chaincode {{ CC_NAME }}:{{ CC_VERSION }} onto {{ installpeer.fullname }}"

- name: Select right cc install file
  set_fact:
    isuffix: "{{ (fabric.release is version('2.0', '>='))|ternary('2', '')}}"

- name: Create chaincode install script
  template:
    src: "{{ pjroot }}/playbooks/ops/templates/ccinstall{{isuffix}}.j2"
    dest: "{{ pjroot }}/vars/run/ccinstall.{{ installpeer.fullname }}.sh"
    mode: +x

- name: Run the chaincode install script on cli container
  command: >-
    docker exec cli /vars/run/ccinstall.{{installpeer.fullname}}.sh
  register: result

- name: Set the status flag based on the return value
  set_fact:
    status_flag: "{{ (result.rc == 0)|ternary('Success', 'Failure') }}"