---
- name: "Process keys"
  include_tasks: "{{ pjroot }}/playbooks/common/processkeys.yaml"

- name: Create profiles
  template:
    src: "{{ pjroot }}/playbooks/ops/profilegen/templates/{{ item.name }}"
    dest: "{{ pjroot }}/vars/{{ item.target }}"
  with_items:
    - "{{ {'name': 'pyprofile.j2', 'target': CHANNEL_NAME+'_network.json'} }}"
    - "{{ {'name': 'goprofile.j2', 'target': CHANNEL_NAME+'_connection.json'} }}"
    - "{{ {'name': 'goprofileyaml.j2', 'target': CHANNEL_NAME+'_connection.yaml'} }}"
    - "{{ {'name': 'endpoints.j2', 'target': 'endpoints.yaml'} }}"
    - "{{ {'name': 'vscodenodefile.j2', 'target': 'vscodenodefile.json'} }}"
