---
- name: Select an orderer for peer channel join.
  when: allorderers|length > 0
  set_fact:
    actingorderer: "{{ allorderers | random }}"

- name: Select an orderer for peer channel join.
  when: allorderers|length == 0 and ext_orderers is defined
  set_fact:
    actingorderer: "{{ ext_orderers | random }}"

- name: Select a peer for channel query.
  set_fact:
    actingpeer: "{{ allpeers|selectattr('org','equalto',CURRENT_ORG)|list|random }}"
    isuffix: "{{ (fabric.release is version('2.0', '>='))|ternary('2', '')}}"

- name: Create channel query script
  template:
    src: "{{ pjroot }}/playbooks/ops/templates/channelquery.j2"
    dest: "{{ pjroot }}/vars/run/channelquery.sh"
    mode: +x

- name: Run the channel query script on cli container
  command: >-
    docker exec cli /vars/run/channelquery.sh

- name: Channel configuration query results
  debug:
    msg: "Channel configuration file: ./vars/{{ CHANNEL_NAME }}_config.json"
  tags: [print_action]
