- name: Get external orderer endpoints and certs
  include_vars:
    file: "{{ pjroot }}/vars/orderendpoints.yaml"
    name: ex_orderers

- name: Add external orderers to the orderer list
  set_fact:
    allorderers: |
      {{ allorderers + [{ 'org':item.org, 'name':item.name, 'fullname': item.fullname, 'type': 'orderer' }] }}
  with_items: "{{ ex_orderers.ordererEndpoints }}"
  no_log: True

- name: Create orderer cert directory
  file:
    path: "{{ pjroot }}/vars/keyfiles/ordererOrganizations/{{ item.org }}/orderers/{{ item.fullname }}/tls"
    state: "directory"
  with_items: "{{ ex_orderers.ordererEndpoints }}"
  no_log: True

- name: Save external orderer certificates
  copy:
    dest: "{{ pjroot}}/vars/keyfiles/ordererOrganizations/{{ item.org }}/orderers/{{item.fullname}}/tls/server.crt"
    content: |
      {{ item.tlsCACerts | b64decode }}
  with_items: "{{ ex_orderers.ordererEndpoints }}"
  no_log: True