- name: Select an orderer from local orderer nodes
  when: allorderers|length > 0
  set_fact:
    actingorderer: "{{ allorderers | random }}"

- name: Select an orderer from external orderer nodes
  when: (allorderers|length) == 0 and (ext_orderers|length) > 0
  set_fact:
    actingorderer: "{{ ext_orderers | random }}"
