---
- name: Initialize the success flag
  set_fact:
    status_flag: "Success"

- name: Select an orderer for chaincode install
  set_fact:
    actingorderer: "{{ allorderers | random }}"
    actingpeer: "{{ allpeers|selectattr('org','equalto',CURRENT_ORG)|list|random }}"
    isuffix: "{{ (fabric.release is version('2.0', '>='))|ternary('2', '')}}"

- name: Create chaincode invocation script
  template:
    src: "{{ pjroot }}/playbooks/ops/templates/ccinvoke.j2"
    dest: "{{ pjroot }}/vars/run/ccinvoke.sh"
    mode: +x

- name: Run the chaincode invoke script on cli container
  command: >-
    docker exec cli /vars/run/ccinvoke.sh
  register: theresult

- name: "Chaincode invocation results"
  debug:
    msg: "{{ theresult.stderr_lines }}"
  tags: [print_action]

