---
- debug:
    msg: "Joining peer {{ joinpeer.fullname }} to channel {{ CHANNEL_NAME }}"

- name: Select an orderer for peer channel join.
  set_fact:
    actingorderer: "{{ allorderers | random }}"
    actingpeer: "{{ joinpeer }}"

- name: Create chanel join script
  template:
    src: "{{ pjroot }}/playbooks/ops/templates/channeljoin.j2"
    dest: "{{ pjroot }}/vars/run/channeljoin.{{ actingpeer.fullname }}.sh"
    mode: +x

- name: Run the channel join script on cli container
  command: >-
    docker exec cli /vars/run/channeljoin.{{ actingpeer.fullname }}.sh
  register: result

- name: Set the status flag based on the return value
  set_fact:
    status_flag: "{{ (result.rc == 0)|ternary('Success', 'Failure') }}"

