---
- name: Select an orderer for chaincode approval
  when: allorderers|length > 0
  set_fact:
    actingorderer: "{{ allorderers | random }}"

- name: Select an orderer for chaincode approval
  when: (allorderers|length) == 0 and (ext_orderers|length) > 0
  set_fact:
    actingorderer: "{{ ext_orderers | random }}"

- name: Select a peer for chaincode status query.
  set_fact:
    actingpeer: "{{ allpeers|selectattr('org','equalto',CURRENT_ORG)|list|random }}"

- name: Create channel sign off script
  template:
    src: "{{ pjroot }}/playbooks/ops/templates/ccapprove.j2"
    dest: "{{ pjroot }}/vars/run/ccapprove.sh"
    mode: +x
  when: fabric.release is version('2.0', '>=')

- name: Run the channel signing off script on cli container
  command: >-
    docker exec cli /vars/run/ccapprove.sh
  when: fabric.release is version('2.0', '>=')
