OPNAMES:
  ccinstall: "cc install"
  ccapprove: "cc approve"
  ccinstantiate: "cc instantiate"
  ccinvoke: "cc invoke"
  channelcreate: "channel create"
  channeljoin: "channel join"
  blockquery: "block query"
  channelquery: "channel query"
  profilegen: "profile generation"
  channelsign: "channel signoff"
  channelupdate: "channel update"
  anchorupdate: "anchor update"
  dashup: "dashboard up"
  dashdown: "dashboard down"